### ISSUE TITLE
How do you run this

### ISSUE THREAD

**Issue by ajayeola** [garagesteve1155/function_former#1]
Where are the instructions for running this?

**Comment by garagesteve1155** [comment]
It can be ran like any python script. You may have to install some modules through pip before you can run it.

**Comment by garagesteve1155** [comment]
Full instructions are coming soon. 

Make sure python is installed on your computer.
Install any modules from the script that you dont already have.
Run the script, the script will ask you questions from there.
Finished code will be in the same folder as this script and will be named generated_code.py
